package com.project.api.dto.response;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

@Builder
@AllArgsConstructor
@Getter
@Setter
@ToString
public class UserDeviceDTO {
    private String id;
    private String userId;
    private String email;
    private String deviceId;
}
